import { dashboardStateHelperScript } from './state.ts';

export function renderDashboardScript(token = ''): string {
  const escapedToken = JSON.stringify(token);
  return String.raw`${dashboardStateHelperScript()}
const DASHBOARD_TOKEN=${escapedToken};
const WRITE_HEADERS={'content-type':'application/json','x-nectar-dashboard-token':DASHBOARD_TOKEN};
let state=null,current=null,ui=createDashboardUiState({theme:readThemePreference()});
const $=(id)=>document.getElementById(id);
function dispatch(action){ ui=reduceDashboardUiState(ui,action); applyUiPreferences(); return ui; }
function readThemePreference(){ try{ const value=localStorage.getItem('nectar-dashboard-theme'); return value==='light'||value==='dark'||value==='system'?value:'system'; }catch(_err){ return 'system'; } }
function writeThemePreference(theme){ try{ localStorage.setItem('nectar-dashboard-theme',theme); }catch(_err){} }
function cycleTheme(){ const next=ui.theme==='system'?'light':ui.theme==='light'?'dark':'system'; dispatch({type:'theme/set',theme:next}); writeThemePreference(next); }
function applyUiPreferences(){ document.documentElement.dataset.theme=ui.theme; document.body.classList.toggle('densityCompact',ui.density==='compact'); const themeButton=$('theme'); if(themeButton){ themeButton.textContent=ui.theme==='dark'?'D':ui.theme==='light'?'L':'S'; themeButton.title='Theme: '+ui.theme; themeButton.setAttribute('aria-label','Theme: '+ui.theme); } }
async function load(){ dispatch({type:'load/start'}); $('sync').textContent='reading files...'; $('contentPanel').setAttribute('aria-busy','true'); renderStatePanel('loading'); const params=new URLSearchParams({posts_page:String(ui.postsPage),pages_page:String(ui.pagesPage),per_page:'12'}); if(ui.query)params.set('search',ui.query); if(ui.statusFilter)params.set('status',ui.statusFilter); try{ const r=await fetch('/api/state?'+params); if(!r.ok) throw new Error('State request failed with '+r.status); state=await r.json(); dispatch({type:'load/success'}); render(); $('sync').textContent='synced '+new Date(state.generatedAt).toLocaleTimeString(); }catch(err){ dispatch({type:'load/error',message:err instanceof Error?err.message:String(err)}); $('sync').textContent='load failed'; renderStatePanel('error',ui.lastError); }finally{ $('contentPanel').setAttribute('aria-busy','false'); } }
function render(){ if(!state){ renderStatePanel(ui.loadStatus==='error'?'error':'loading',ui.lastError); return; } $('siteTitle').textContent=state.site.title; $('siteSub').textContent=state.site.description || state.site.url; $('postCount').textContent=state.posts.total; $('pageCount').textContent=state.pages.total; $('authorCount').textContent=state.authors.total; $('tagCount').textContent=state.tags.total; document.querySelectorAll('.nav button').forEach(b=>{ const active=b.dataset.view===ui.view; b.classList.toggle('active',active); if(active)b.setAttribute('aria-current','page'); else b.removeAttribute('aria-current'); }); if(ui.view==='settings') return renderSettings(); if(ui.view==='authors'||ui.view==='tags') return renderTax(ui.view); renderContent(ui.view); }
function renderContent(kind){ const list=state[kind]; $('kicker').textContent=kind+' · created newest first'; $('newItem').style.display='inline-block'; const rows=list.items.map(item=>'<tr><td class="titleCell"><b>'+escapeHtml(item.title)+'</b><div class="slug">'+escapeHtml(item.slug)+'</div>'+warningBadge(item)+'</td><td><span class="pill '+(item.status==='draft'?'draft':'')+'">'+escapeHtml(item.status)+'</span></td><td>'+date(item.createdAt)+'</td><td><div class="pathText">'+escapeHtml(item.path)+'</div></td><td><button class="btn secondary" data-edit="'+escapeAttr(item.slug)+'">Edit</button></td></tr>').join(''); $('contentPanel').innerHTML='<div class="panelHead"><h2>'+escapeHtml(kind)+'</h2><span class="meta">page '+list.page+' of '+list.pages+'</span></div><div class="settingsGrid"><label class="field wide"><span>Search title, slug, path, tags, authors</span><input id="contentSearch" value="'+escapeAttr(ui.query)+'"></label><label class="field"><span>Status</span><select id="statusFilter"><option value="">Any</option><option value="published">Published</option><option value="draft">Draft</option><option value="scheduled">Scheduled</option></select></label></div>'+(rows?'<div class="tableWrap"><table class="table"><thead><tr><th>Title</th><th>Status</th><th>Created</th><th>Path</th><th><span class="srOnly">Actions</span></th></tr></thead><tbody>'+rows+'</tbody></table></div>':renderStatePanelHtml('empty'))+'<div class="pager"><button class="btn secondary" id="prev" '+(list.page<=1?'disabled':'')+'>Prev</button><button class="btn secondary" id="next" '+(list.page>=list.pages?'disabled':'')+'>Next</button><span class="meta">'+state.settings.operations.search.resultCount+' result(s)</span></div>'; $('statusFilter').value=ui.statusFilter; $('contentSearch').oninput=(e)=>{ dispatch({type:'search/set',query:e.target.value}); $('search').value=ui.query; clearTimeout(window.__nectarSearchTimer); window.__nectarSearchTimer=setTimeout(load,180); }; $('statusFilter').onchange=(e)=>{ dispatch({type:'status/set',statusFilter:e.target.value}); load(); }; $('prev').onclick=()=>{ if(list.page<=1)return; dispatch({type:'page/prev',kind}); load(); }; $('next').onclick=()=>{ if(list.page>=list.pages)return; dispatch({type:'page/next',kind,pages:list.pages}); load(); }; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(kind,b.dataset.edit)); }
function renderTax(kind){ const list=state[kind]; const q=ui.query.toLowerCase(); const items=list.items.filter(item=>matches(item.name+' '+item.slug+' '+item.path+' '+item.url,q)); $('kicker').textContent=kind+' · taxonomy files'; $('newItem').style.display='inline-block'; const rows=items.map(item=>'<tr><td class="titleCell"><b>'+escapeHtml(item.name)+'</b><div class="slug">'+escapeHtml(item.slug)+'</div><div class="meta">'+escapeHtml(item.description||'')+'</div></td><td>'+item.count+'</td><td><span class="pill '+(item.source==='generated'?'draft':'')+'">'+escapeHtml(item.source||'file')+(item.orphaned?' · orphaned':'')+'</span></td><td><div class="pathText">'+escapeHtml(item.path||item.materializePath||'generated from content references')+'</div></td><td>'+(item.editable?'<button class="btn secondary" data-edit="'+escapeAttr(item.slug)+'">Edit</button>':'<button class="btn secondary" data-materialize="'+escapeAttr(item.slug)+'">Create file</button>')+'</td></tr>').join(''); $('contentPanel').innerHTML='<div class="panelHead"><h2>'+escapeHtml(kind)+'</h2><span class="meta">'+list.total+' records</span></div>'+(rows?'<div class="tableWrap"><table class="table"><thead><tr><th>Name</th><th>Posts</th><th>Source</th><th>Path</th><th><span class="srOnly">Actions</span></th></tr></thead><tbody>'+rows+'</tbody></table></div>':renderStatePanelHtml('empty','No taxonomy files match this view.')); document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(kind,b.dataset.edit)); document.querySelectorAll('[data-materialize]').forEach(b=>b.onclick=()=>materializeTaxonomy(kind,b.dataset.materialize)); }
function renderSettings(){ $('kicker').textContent='settings · searchable cards'; $('newItem').style.display='none'; const s=state.settings; const cards=s.cards||[]; $('contentPanel').innerHTML='<div class="panelHead"><h2>Project settings</h2><span class="meta">'+escapeHtml(s.configPath)+'</span></div><div class="settingsGrid"><label class="field"><span>Search settings</span><input id="settingsSearch" placeholder="Press / to search" value=""></label><label class="field"><span>Site title</span><input id="setTitle" value="'+escapeAttr(state.site.title)+'"></label><label class="field"><span>Accent color</span><input id="setAccent" value="'+escapeAttr(state.site.accentColor)+'"></label><label class="field wide"><span>Description</span><input id="setDescription" value="'+escapeAttr(state.site.description)+'"></label><label class="field wide"><span>Site URL</span><input id="setUrl" value="'+escapeAttr(state.site.url)+'"></label><div class="field wide"><span id="settingsNotice" class="notice" role="status" aria-live="polite"></span><button class="btn" id="saveSettings">Save site card</button></div></div><div class="settingsGrid" id="settingsCards"></div>'; $('saveSettings').onclick=saveSettings; $('settingsSearch').oninput=()=>renderSettingsCards(cards,$('settingsSearch').value); renderSettingsCards(cards,''); }
function renderSettingsCards(cards,term){ const q=String(term||'').toLowerCase(); const filtered=cards.filter(card=>(card.section+' '+card.title+' '+card.summary+' '+card.source+' '+card.values.map(v=>v.label+' '+v.value).join(' ')).toLowerCase().includes(q)); $('settingsCards').innerHTML=filtered.length?filtered.map(card=>'<article class="settingsCard"><div><h3>'+escapeHtml(card.title)+'</h3><span class="pill '+(card.status==='warn'||card.status==='danger'?'draft':'')+'">'+escapeHtml(card.section)+'</span></div><p class="meta">'+escapeHtml(card.summary)+'</p><div class="slug">'+escapeHtml(card.source)+'</div><table class="table"><tbody>'+card.values.map(v=>'<tr><th>'+escapeHtml(v.label)+'</th><td>'+escapeHtml(v.value)+'</td></tr>').join('')+'</tbody></table>'+(card.command?'<div class="meta">'+escapeHtml(card.command)+'</div>':'')+'</article>').join(''):renderStatePanelHtml('empty','No settings match this search.'); }
async function openEditor(kind,slug){ const r=await fetch('/api/content/'+kind+'/'+slug); if(!r.ok){ renderStatePanel('error','Could not open '+slug); return; } current=await r.json(); $('editorTitle').textContent=current.path; $('editTitle').value=current.frontmatter.title||current.frontmatter.name||''; $('editStatus').value=current.frontmatter.status||'published'; $('editStatus').disabled=kind!=='posts'&&kind!=='pages'; $('editBody').value=current.body; $('notice').textContent=''; renderEditorWarnings(); $('editor').classList.add('open'); $('editTitle').focus(); }
async function saveEditor(){ if(!current)return; const fm={...current.frontmatter}; if(current.kind==='posts'||current.kind==='pages'){ fm.title=$('editTitle').value; fm.status=$('editStatus').value; fm.updated_at=new Date().toISOString(); } else { fm.name=$('editTitle').value; } const r=await fetch('/api/content/'+current.kind+'/'+current.slug,{method:'PUT',headers:WRITE_HEADERS,body:JSON.stringify({fingerprint:current.fingerprint,frontmatter:fm,body:$('editBody').value})}); const data=await r.json(); if(r.status===409){ dispatch({type:'conflict',message:'This file changed on disk. Reloaded latest version; review before saving.'}); current=data.current; $('notice').textContent=ui.conflictMessage; $('editBody').value=current.body; return; } if(!r.ok){ $('notice').textContent=data.error||'Could not save file'; return; } current=null; $('editor').classList.remove('open'); await load(); }
async function saveSettings(){ const updates={title:$('setTitle').value,description:$('setDescription').value,url:$('setUrl').value,accent_color:$('setAccent').value}; const r=await fetch('/api/settings/site',{method:'PATCH',headers:WRITE_HEADERS,body:JSON.stringify({fingerprint:state.settings.fingerprint,updates})}); const data=await r.json(); if(r.status===409){ dispatch({type:'conflict',message:'nectar.toml changed on disk. Reloaded latest settings; review before saving.'}); $('settingsNotice').textContent=ui.conflictMessage; await load(); return; } if(!r.ok){ $('settingsNotice').textContent=data.error||'Could not save settings'; return; } await load(); if($('settingsNotice')) $('settingsNotice').textContent='Saved to nectar.toml'; }
async function materializeTaxonomy(kind,slug){ const r=await fetch('/api/taxonomy/'+kind+'/'+slug+'/file',{method:'POST',headers:WRITE_HEADERS}); if(!r.ok){ alert((await r.json()).error||'Could not create taxonomy file'); return; } await load(); }
async function createItem(){ const title=prompt('Title or name'); if(!title)return; const kind=ui.view==='settings'?'posts':ui.view; const r=await fetch('/api/content',{method:'POST',headers:WRITE_HEADERS,body:JSON.stringify({kind,title})}); if(!r.ok){ alert((await r.json()).error||'Could not create file'); return; } await load(); }
function warningBadge(item){ return item.warnings&&item.warnings.length?'<span class="warnBadge">'+item.warnings.length+' warning'+(item.warnings.length===1?'':'s')+'</span>':''; }
function renderEditorWarnings(){ const text=($('editBody').value||''); const warnings=[]; if(/!\[\s*\]\(/.test(text)) warnings.push('Markdown image has empty alt text.'); if(/<img\b(?![^>]*\salt=)[^>]*>/i.test(text)) warnings.push('HTML image is missing an alt attribute.'); $('editorWarnings').textContent=warnings.join(' '); $('editorWarnings').classList.toggle('active',warnings.length>0); }
function renderStatePanel(kind,message){ $('contentPanel').innerHTML=renderStatePanelHtml(kind,message); }
function renderStatePanelHtml(kind,message){ const copy={loading:['Reading files','Loading the latest saved Markdown and config state from disk.'],error:['Dashboard could not load',message||'Keep your files unchanged and refresh after fixing the reported problem.'],conflict:['External change detected',message||'The file changed on disk. Reloaded latest content so you can review before saving.'],empty:['No files match this view',message||'Try a different search, status filter, or section.']}[kind]||['Dashboard state',message||'']; const action=kind==='error'?'<button class="btn secondary" data-state-action="refresh">Refresh</button>':''; return '<div class="statePanel '+escapeAttr(kind)+'" role="status" aria-live="polite"><b>'+escapeHtml(copy[0])+'</b><p>'+escapeHtml(copy[1])+'</p>'+action+'</div>'; }
function matches(text,query){ return !query || String(text).toLowerCase().includes(query); }
function setView(next){ dispatch({type:'view/set',view:next}); $('search').value=''; closePalette(); load(); }
function openPalette(){ $('paletteModal').classList.add('open'); const first=$('paletteModal').querySelector('button'); if(first) first.focus(); }
function closePalette(){ $('paletteModal').classList.remove('open'); }
function date(v){ return new Date(v).toLocaleDateString(); }
function escapeHtml(v){ return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function escapeAttr(v){ return escapeHtml(v).replace(/"/g,'&quot;'); }
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('search').oninput=(event)=>{ dispatch({type:'search/set',query:event.target.value}); if(ui.view==='posts'||ui.view==='pages'){ clearTimeout(window.__nectarSearchTimer); window.__nectarSearchTimer=setTimeout(load,180); } else { render(); } };
$('density').onclick=()=>{ dispatch({type:'density/toggle'}); render(); };
$('theme').onclick=cycleTheme;
$('command').onclick=openPalette;
$('closePalette').onclick=closePalette;
document.querySelectorAll('[data-command-view]').forEach(b=>b.onclick=()=>setView(b.dataset.commandView));
document.querySelectorAll('[data-command-action]').forEach(b=>b.onclick=()=>{ closePalette(); load(); });
document.addEventListener('click',(event)=>{ if(event.target?.dataset?.stateAction==='refresh') load(); });
$('refresh').onclick=load;
$('newItem').onclick=createItem;
$('closeEditor').onclick=()=>$('editor').classList.remove('open');
$('saveEditor').onclick=saveEditor;
$('editBody').oninput=renderEditorWarnings;
document.addEventListener('keydown',(event)=>{ if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){ event.preventDefault(); openPalette(); } if(event.key==='/'&&ui.view==='settings'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName||'')){ event.preventDefault(); $('settingsSearch')?.focus(); } if(event.key==='Escape'){ closePalette(); $('editor').classList.remove('open'); } });
applyUiPreferences();
new EventSource('/api/events').addEventListener('sync',()=>load());
load();`;
}
