import { dashboardStateHelperScript } from './state.ts';

export function renderDashboardScript(token = ''): string {
  const escapedToken = JSON.stringify(token);
  return String.raw`${dashboardStateHelperScript()}
const DASHBOARD_TOKEN=${escapedToken};
const WRITE_HEADERS={'content-type':'application/json','x-nectar-dashboard-token':DASHBOARD_TOKEN};
const NECTAR_DRAFT_PREFIX='nectar:dashboard:draft:';
const NECTAR_REVISION_PREFIX='nectar:dashboard:revision:';
let state=null,current=null,editorBaseline=null,pendingDraft=null,lastGhostImportResult=null,lastPageBundleImportResult=null,siteSettingsDirty=false,themeSettingsDirty=false,currentDraftKey='',currentRevisionKey='',ui=createDashboardUiState({theme:readThemePreference()});
const $=(id)=>document.getElementById(id);
function dispatch(action){ ui=reduceDashboardUiState(ui,action); applyUiPreferences(); return ui; }
function readThemePreference(){ try{ const value=localStorage.getItem('nectar-dashboard-theme'); return value==='light'||value==='dark'||value==='system'?value:'system'; }catch(_err){ return 'system'; } }
function writeThemePreference(theme){ try{ localStorage.setItem('nectar-dashboard-theme',theme); }catch(_err){} }
function cycleTheme(){ const next=ui.theme==='system'?'light':ui.theme==='light'?'dark':'system'; dispatch({type:'theme/set',theme:next}); writeThemePreference(next); }
function applyUiPreferences(){ document.documentElement.dataset.theme=ui.theme; document.body.classList.toggle('densityCompact',ui.density==='compact'); const themeButton=$('theme'); if(themeButton){ themeButton.textContent=ui.theme==='dark'?'D':ui.theme==='light'?'L':'S'; themeButton.title='Theme: '+ui.theme; themeButton.setAttribute('aria-label','Theme: '+ui.theme); } }
async function load(options){ if(!(options&&options.force)&&!confirmDiscardChanges('Refresh files? Unsaved settings will be discarded; unsaved editor changes stay only in this browser draft until you save.'))return; dispatch({type:'load/start'}); $('sync').textContent='reading files...'; $('contentPanel').setAttribute('aria-busy','true'); renderStatePanel('loading'); const params=new URLSearchParams({posts_page:String(ui.postsPage),pages_page:String(ui.pagesPage),per_page:'12'}); if(ui.query)params.set('search',ui.query); if(ui.statusFilter)params.set('status',ui.statusFilter); try{ const r=await fetch('/api/state?'+params); if(!r.ok) throw new Error('State request failed with '+r.status); state=await r.json(); dispatch({type:'load/success'}); render(); $('sync').textContent='synced '+new Date(state.generatedAt).toLocaleTimeString(); }catch(err){ dispatch({type:'load/error',message:err instanceof Error?err.message:String(err)}); $('sync').textContent='load failed'; renderStatePanel('error',ui.lastError); }finally{ $('contentPanel').setAttribute('aria-busy','false'); } }
function render(){ if(!state){ renderStatePanel(ui.loadStatus==='error'?'error':'loading',ui.lastError); return; } $('siteTitle').textContent=state.site.title; $('siteSub').textContent=state.site.description || state.site.url; $('postCount').textContent=state.posts.total; $('pageCount').textContent=state.pages.total; $('authorCount').textContent=state.authors.total; $('tagCount').textContent=state.tags.total; document.querySelectorAll('.nav button').forEach(b=>{ const active=b.dataset.view===ui.view; b.classList.toggle('active',active); if(active)b.setAttribute('aria-current','page'); else b.removeAttribute('aria-current'); }); if(ui.view==='settings') return renderSettings(); if(ui.view==='authors'||ui.view==='tags') return renderTax(ui.view); renderContent(ui.view); }
function renderContent(kind){ const list=state[kind]; $('kicker').textContent=kind+' · created newest first'; $('newItem').style.display='inline-block'; const rows=list.items.map(item=>'<tr><td class="titleCell"><b>'+escapeHtml(item.title)+'</b><div class="slug">'+escapeHtml(item.slug)+'</div>'+warningBadge(item)+'</td><td><span class="pill '+(item.status==='draft'?'draft':'')+'">'+escapeHtml(item.status)+'</span></td><td>'+date(item.createdAt)+'</td><td>'+previewCell(item)+'</td><td><div class="pathText">'+escapeHtml(item.path)+'</div></td><td><button class="btn secondary" data-edit="'+escapeAttr(item.slug)+'">Edit</button>'+(kind==='pages'?' <button class="btn secondary" data-export-page="'+escapeAttr(item.slug)+'">Export</button>':'')+'</td></tr>').join(''); $('contentPanel').innerHTML='<div class="panelHead"><h2>'+escapeHtml(kind)+'</h2><span class="meta">page '+list.page+' of '+list.pages+'</span></div><div class="settingsGrid"><label class="field wide"><span>Search title, slug, path, tags, authors</span><input id="contentSearch" value="'+escapeAttr(ui.query)+'"></label><label class="field"><span>Status</span><select id="statusFilter"><option value="">Any</option><option value="published">Published</option><option value="draft">Draft</option><option value="scheduled">Scheduled</option></select></label></div>'+(rows?'<div class="tableWrap"><table class="table"><thead><tr><th>Title</th><th>Status</th><th>Created</th><th>Preview</th><th>Path</th><th><span class="srOnly">Actions</span></th></tr></thead><tbody>'+rows+'</tbody></table></div>':renderStatePanelHtml('empty'))+'<div class="pager"><button class="btn secondary" id="prev" '+(list.page<=1?'disabled':'')+'>Prev</button><button class="btn secondary" id="next" '+(list.page>=list.pages?'disabled':'')+'>Next</button><span class="meta">'+state.settings.operations.search.resultCount+' result(s)</span></div>'; $('statusFilter').value=ui.statusFilter; $('contentSearch').oninput=(e)=>{ dispatch({type:'search/set',query:e.target.value}); $('search').value=ui.query; clearTimeout(window.__nectarSearchTimer); window.__nectarSearchTimer=setTimeout(load,180); }; $('statusFilter').onchange=(e)=>{ dispatch({type:'status/set',statusFilter:e.target.value}); load(); }; $('prev').onclick=()=>{ if(list.page<=1)return; dispatch({type:'page/prev',kind}); load(); }; $('next').onclick=()=>{ if(list.page>=list.pages)return; dispatch({type:'page/next',kind,pages:list.pages}); load(); }; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(kind,b.dataset.edit)); document.querySelectorAll('[data-export-page]').forEach(b=>b.onclick=()=>exportPageBundle(b.dataset.exportPage)); }
function renderTax(kind){ const list=state[kind]; const q=ui.query.toLowerCase(); const items=list.items.filter(item=>matches(item.name+' '+item.slug+' '+item.path+' '+item.url,q)); $('kicker').textContent=kind+' · taxonomy files'; $('newItem').style.display='inline-block'; const rows=items.map(item=>'<tr><td class="titleCell"><b>'+escapeHtml(item.name)+'</b><div class="slug">'+escapeHtml(item.slug)+'</div><div class="meta">'+escapeHtml(item.description||'')+'</div></td><td>'+item.count+'</td><td><span class="pill '+(item.source==='generated'?'draft':'')+'">'+escapeHtml(item.source||'file')+(item.orphaned?' · orphaned':'')+'</span></td><td><div class="pathText">'+escapeHtml(item.path||item.materializePath||'generated from content references')+'</div></td><td>'+(item.editable?'<button class="btn secondary" data-edit="'+escapeAttr(item.slug)+'">Edit</button>':'<button class="btn secondary" data-materialize="'+escapeAttr(item.slug)+'">Create file</button>')+'</td></tr>').join(''); $('contentPanel').innerHTML='<div class="panelHead"><h2>'+escapeHtml(kind)+'</h2><span class="meta">'+list.total+' records</span></div>'+(rows?'<div class="tableWrap"><table class="table"><thead><tr><th>Name</th><th>Posts</th><th>Source</th><th>Path</th><th><span class="srOnly">Actions</span></th></tr></thead><tbody>'+rows+'</tbody></table></div>':renderStatePanelHtml('empty','No taxonomy files match this view.')); document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(kind,b.dataset.edit)); document.querySelectorAll('[data-materialize]').forEach(b=>b.onclick=()=>materializeTaxonomy(kind,b.dataset.materialize)); }
function renderSettings(){ $('kicker').textContent='settings · searchable cards'; $('newItem').style.display='none'; const s=state.settings; const cards=s.cards||[]; siteSettingsDirty=false; themeSettingsDirty=false; $('contentPanel').innerHTML='<div class="panelHead"><h2>Project settings</h2><span class="meta">'+escapeHtml(s.configPath)+'</span></div><div class="settingsGrid"><label class="field"><span>Search settings</span><input id="settingsSearch" placeholder="Press / to search" value=""></label><label class="field"><span>Site title</span><input id="setTitle" value="'+escapeAttr(state.site.title)+'"></label><label class="field"><span>Accent color</span><input id="setAccent" value="'+escapeAttr(state.site.accentColor)+'"></label><label class="field wide"><span>Description</span><input id="setDescription" value="'+escapeAttr(state.site.description)+'"></label><label class="field wide"><span>Site URL</span><input id="setUrl" value="'+escapeAttr(state.site.url)+'"></label><div class="field wide"><span id="settingsNotice" class="notice" role="status" aria-live="polite"></span><button class="btn" id="saveSettings">Save site card</button></div></div>'+renderThemeSwitcherPanel(s)+renderPageBundleImportPanel()+renderGhostImportPanel()+'<div class="settingsGrid" id="settingsCards"></div>'; $('saveSettings').onclick=saveSettings; $('saveThemeSettings').onclick=saveThemeSettings; updateThemeSaveState(); $('settingsSearch').oninput=()=>renderSettingsCards(cards,$('settingsSearch').value); ['setTitle','setAccent','setDescription','setUrl'].forEach(id=>$(id).oninput=()=>{ siteSettingsDirty=true; }); if($('settingsThemeName')) $('settingsThemeName').onchange=()=>{ themeSettingsDirty=true; updateThemeSaveState(); }; bindPageBundleImportControls(); bindGhostImportControls(); if(lastPageBundleImportResult) renderPageBundleImportResult(lastPageBundleImportResult); if(lastGhostImportResult) renderGhostImportResult(lastGhostImportResult); renderSettingsCards(cards,''); }
function renderThemeSwitcherPanel(settings){ const theme=typeof settings.theme==='object'&&settings.theme?settings.theme:{name:String(settings.theme||''),dir:'themes',available:[]}; const activeExists=(theme.available||[]).some(item=>item.name===theme.name); const missingActive=theme.name&&!activeExists; const missingOption=missingActive?'<option value="" selected disabled>Missing: '+escapeHtml(theme.name)+'</option>':''; const options=missingOption+(theme.available||[]).map(item=>'<option value="'+escapeAttr(item.name)+'" '+(item.name===theme.name?'selected':'')+'>'+escapeHtml(item.name)+(item.active?' · active':'')+'</option>').join(''); const disabled=options?'':' disabled'; return '<div class="settingsGrid"><article class="settingsCard field wide"><div><h3>Active theme</h3><span class="pill">nectar.toml</span></div><p class="meta">Choose the theme used by the next build and saved previews.</p><div class="fields"><label class="field"><span>Theme directory</span><input value="'+escapeAttr(theme.dir||'themes')+'" disabled></label><label class="field"><span>Theme</span><select id="settingsThemeName" data-current="'+escapeAttr(activeExists?theme.name:'')+'"'+disabled+'>'+options+'</select></label></div><div class="editorActions"><button class="btn" id="saveThemeSettings"'+disabled+'>Save active theme</button><span id="themeSettingsNotice" class="notice" role="status" aria-live="polite"></span></div><div class="meta">'+(options?(missingActive?'Active theme is missing. Choose an installed theme before saving.':'Run nectar build after switching to refresh previews.'):'No theme directories found under '+escapeHtml(theme.dir||'themes')+'.')+'</div></article></div>'; }
function updateThemeSaveState(){ const select=$('settingsThemeName'); const button=$('saveThemeSettings'); if(!select||!button)return; button.disabled=!select.value||select.value===select.dataset.current; }
function renderSettingsCards(cards,term){ const q=String(term||'').toLowerCase(); const filtered=cards.filter(card=>(card.section+' '+card.title+' '+card.summary+' '+card.source+' '+card.values.map(v=>v.label+' '+v.value).join(' ')).toLowerCase().includes(q)); $('settingsCards').innerHTML=filtered.length?filtered.map(card=>'<article class="settingsCard"><div><h3>'+escapeHtml(card.title)+'</h3><span class="pill '+(card.status==='warn'||card.status==='danger'?'draft':'')+'">'+escapeHtml(card.section)+'</span></div><p class="meta">'+escapeHtml(card.summary)+'</p><div class="slug">'+escapeHtml(card.source)+'</div><table class="table"><tbody>'+card.values.map(v=>'<tr><th>'+escapeHtml(v.label)+'</th><td>'+escapeHtml(v.value)+'</td></tr>').join('')+'</tbody></table>'+(card.command?'<div class="meta">'+escapeHtml(card.command)+'</div>':'')+'</article>').join(''):renderStatePanelHtml('empty','No settings match this search.'); }
function renderGhostImportPanel(){ return '<div class="settingsGrid"><article class="settingsCard field wide"><div><h3>Ghost import</h3><span class="pill draft">Review first</span></div><p class="meta">Run a Ghost JSON, folder, or ZIP import from a local path. Preview does not write files.</p><label class="field wide"><span>Export path</span><input id="ghostImportFile" placeholder="/path/to/ghost-export.zip"></label><div class="fields"><label class="field"><span>Conflict policy</span><select id="ghostImportConflict"><option value="skip">skip</option><option value="rename">rename</option><option value="overwrite">overwrite</option></select></label><label class="field"><span>Output dir</span><input id="ghostImportOutput" placeholder="content/"></label></div><div class="editorActions"><button class="btn secondary" id="previewGhostImport">Preview import</button><button class="btn" id="applyGhostImport">Import files</button></div><div class="notice" id="ghostImportNotice" role="status" aria-live="polite"></div><div id="ghostImportResult"></div></article></div>'; }
function renderPageBundleImportPanel(){ return '<div class="settingsGrid"><article class="settingsCard field wide"><div><h3>Page bundle import</h3><span class="pill">Focused</span></div><p class="meta">Import one saved Page collaboration bundle from a local path. Preview does not write files.</p><label class="field wide"><span>Bundle path</span><input id="pageBundleImportFile" placeholder="/path/to/about.page.json"></label><div class="fields"><label class="field"><span>Conflict policy</span><select id="pageBundleImportConflict"><option value="skip">skip</option><option value="rename">rename</option><option value="overwrite">overwrite</option></select></label></div><div class="editorActions"><button class="btn secondary" id="previewPageBundleImport">Preview import</button><button class="btn" id="applyPageBundleImport">Import page</button></div><div class="notice" id="pageBundleImportNotice" role="status" aria-live="polite"></div><div id="pageBundleImportResult"></div></article></div>'; }
function bindPageBundleImportControls(){ $('previewPageBundleImport').onclick=()=>runPageBundleImport(true); $('applyPageBundleImport').onclick=()=>runPageBundleImport(false); }
function readPageBundleImportPayload(dryRun){ return {file:$('pageBundleImportFile').value.trim(),dryRun,onConflict:$('pageBundleImportConflict').value}; }
async function runPageBundleImport(dryRun){ const payload=readPageBundleImportPayload(dryRun); if(!payload.file){ lastPageBundleImportResult={error:'Page bundle path is required.'}; renderPageBundleImportResult(lastPageBundleImportResult); return; } if(!dryRun&&payload.onConflict==='overwrite'&&!confirm('Overwrite an existing page if the bundle slug already exists?'))return; if(!dryRun&&!confirm('Import writes one Page and bundled assets into this project. Continue?'))return; $('previewPageBundleImport').disabled=true; $('applyPageBundleImport').disabled=true; $('pageBundleImportNotice').textContent=dryRun?'Previewing page import...':'Importing page...'; try{ const r=await fetch('/api/page-bundles/import',{method:'POST',headers:WRITE_HEADERS,body:JSON.stringify(payload)}); const data=await r.json(); if(!r.ok){ lastPageBundleImportResult={error:data.error||'Page import failed'}; renderPageBundleImportResult(lastPageBundleImportResult); return; } lastPageBundleImportResult=data; renderPageBundleImportResult(lastPageBundleImportResult); if(!dryRun) await load({force:true}); }catch(err){ lastPageBundleImportResult={error:err instanceof Error?err.message:String(err)}; renderPageBundleImportResult(lastPageBundleImportResult); }finally{ if($('previewPageBundleImport'))$('previewPageBundleImport').disabled=false; if($('applyPageBundleImport'))$('applyPageBundleImport').disabled=false; if($('pageBundleImportNotice'))$('pageBundleImportNotice').textContent=''; } }
function renderPageBundleImportResult(result){ const box=$('pageBundleImportResult'); if(!box)return; if(result.error){ box.innerHTML='<div class="statePanel error"><b>Import failed</b><p>'+escapeHtml(result.error)+'</p></div>'; return; } const r=result.result||{}; const rows=[['mode',result.dryRun?'dry-run':'apply'],['page path',r.pagePath||''],['written',r.written?'yes':'no'],['skipped',r.skipped?'yes':'no'],['renamed',r.renamed?'yes':'no'],['assets',(r.assetPaths||[]).length]]; box.innerHTML='<table class="table"><tbody>'+rows.map(row=>'<tr><th>'+escapeHtml(row[0])+'</th><td>'+escapeHtml(row[1])+'</td></tr>').join('')+'</tbody></table>'; }
async function exportPageBundle(slug){ try{ const r=await fetch('/api/page-bundles/export/'+encodeURIComponent(slug)); const data=await r.json(); if(!r.ok){ alert(data.error||'Could not export page bundle'); return; } const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=slug+'.page.json'; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }catch(err){ alert(err instanceof Error?err.message:String(err)); } }
function bindGhostImportControls(){ $('previewGhostImport').onclick=()=>runGhostImport(true); $('applyGhostImport').onclick=()=>runGhostImport(false); }
function readGhostImportPayload(dryRun){ const outputDir=$('ghostImportOutput').value.trim(); return {file:$('ghostImportFile').value.trim(),dryRun,onConflict:$('ghostImportConflict').value,outputDir:outputDir||undefined}; }
async function runGhostImport(dryRun){ const payload=readGhostImportPayload(dryRun); if(!payload.file){ lastGhostImportResult={error:'Ghost export path is required.'}; renderGhostImportResult(lastGhostImportResult); return; } if(!dryRun&&!confirm('Import writes Markdown and assets into the selected target. Continue?'))return; $('previewGhostImport').disabled=true; $('applyGhostImport').disabled=true; $('ghostImportNotice').textContent=dryRun?'Previewing import...':'Importing files...'; try{ const r=await fetch('/api/import/ghost',{method:'POST',headers:WRITE_HEADERS,body:JSON.stringify(payload)}); const data=await r.json(); if(!r.ok){ lastGhostImportResult={error:data.error||'Import failed'}; renderGhostImportResult(lastGhostImportResult); return; } lastGhostImportResult=data; renderGhostImportResult(lastGhostImportResult); if(!dryRun) await load({force:true}); }catch(err){ lastGhostImportResult={error:err instanceof Error?err.message:String(err)}; renderGhostImportResult(lastGhostImportResult); }finally{ if($('previewGhostImport'))$('previewGhostImport').disabled=false; if($('applyGhostImport'))$('applyGhostImport').disabled=false; if($('ghostImportNotice'))$('ghostImportNotice').textContent=''; } }
function renderGhostImportResult(result){ const box=$('ghostImportResult'); if(!box)return; if(result.error){ box.innerHTML='<div class="statePanel error"><b>Import failed</b><p>'+escapeHtml(result.error)+'</p></div>'; return; } const s=result.summary||{}; const rows=[['mode',result.mode||''],['target',result.target||'content/'],['posts',s.posts||0],['pages',s.pages||0],['drafts',s.drafts||0],['tags',s.tags||0],['authors',s.authors||0],['assets copied',s.assetsCopied||0],['images downloaded',s.imagesDownloaded||0],['images failed',s.imagesFailed||0],['skipped',s.skipped||0],['overwritten',s.overwritten||0],['renamed',s.renamed||0],['status filtered',s.statusFiltered||0],['tag filtered',s.tagFiltered||0],['date filtered',s.dateFiltered||0],['empty bodies',s.bodiesEmpty||0],['slug collisions',s.slugCollisions||0],['redirects',s.redirectsImported||0],['slug redirects',s.slugRedirects||0],['code injection skipped',s.codeInjectionSkipped||0],['HTML preserved',s.htmlPreserved||0]]; box.innerHTML='<table class="table"><tbody>'+rows.map(row=>'<tr><th>'+escapeHtml(row[0])+'</th><td>'+escapeHtml(row[1])+'</td></tr>').join('')+'</tbody></table>'+(Array.isArray(s.plannedPaths)&&s.plannedPaths.length?'<div class="meta">'+s.plannedPaths.length+' planned path(s)</div>':''); }
async function openEditor(kind,slug){ if(!confirmDiscardChanges('Open another file? Unsaved edits stay only in this browser draft until you save.'))return; const r=await fetch('/api/content/'+kind+'/'+slug); if(!r.ok){ renderStatePanel('error','Could not open '+slug); return; } current=await r.json(); currentDraftKey=draftKey(current); currentRevisionKey=revisionKey(current); applyEditorSnapshot(snapshotFromItem(current)); editorBaseline=editorSnapshot(); pendingDraft=findDraftForCurrent(); $('editorTitle').textContent=current.path; $('editorMeta').textContent=current.path+' · fingerprint '+fingerprintToken(current.fingerprint); $('notice').textContent=''; renderArtifactPreview(findSummary(kind,slug)); renderEditorWarnings(); updateRecoveryControls(); $('editor').classList.add('open'); $('editTitle').focus(); }
async function saveEditor(){ if(!current)return; const fm=buildFrontmatter(); const body=$('editBody').value; recordRevision({frontmatter:{...current.frontmatter},body:current.body,fingerprint:current.fingerprint,path:current.path}); persistDraft(); const r=await fetch('/api/content/'+current.kind+'/'+current.slug,{method:'PUT',headers:WRITE_HEADERS,body:JSON.stringify({fingerprint:current.fingerprint,frontmatter:fm,body})}); const data=await r.json(); if(r.status===409){ dispatch({type:'conflict',message:'This file changed on disk. Your browser draft was kept; review before restoring or saving.'}); current=data.current; currentDraftKey=draftKey(current); currentRevisionKey=revisionKey(current); pendingDraft=findDraftForCurrent(); applyEditorSnapshot(snapshotFromItem(current)); editorBaseline=editorSnapshot(); $('notice').textContent=ui.conflictMessage; renderEditorWarnings(); updateRecoveryControls(); return; } if(!r.ok){ $('notice').textContent=data.error||'Could not save file. Browser draft was kept.'; updateRecoveryControls(); return; } clearDraftsForCurrent(); current=null; editorBaseline=null; pendingDraft=null; $('editor').classList.remove('open'); await load({force:true}); }
async function saveSettings(){ const updates={title:$('setTitle').value,description:$('setDescription').value,url:$('setUrl').value,accent_color:$('setAccent').value}; const r=await fetch('/api/settings/site',{method:'PATCH',headers:WRITE_HEADERS,body:JSON.stringify({fingerprint:state.settings.fingerprint,updates})}); const data=await r.json(); if(r.status===409){ dispatch({type:'conflict',message:'nectar.toml changed on disk. Latest settings loaded; re-enter changes after review.'}); siteSettingsDirty=false; themeSettingsDirty=false; await load({force:true}); if($('settingsNotice')) $('settingsNotice').textContent=ui.conflictMessage; return; } if(!r.ok){ $('settingsNotice').textContent=data.error||'Could not save settings'; return; } if(data.fingerprint) state.settings.fingerprint=data.fingerprint; state.site.title=updates.title; state.site.description=updates.description; state.site.url=updates.url; state.site.accentColor=updates.accent_color; state.settings.site.title=updates.title; state.settings.site.description=updates.description; state.settings.site.url=updates.url; state.settings.site.accentColor=updates.accent_color; siteSettingsDirty=false; if(themeSettingsDirty){ $('settingsNotice').textContent='Saved to nectar.toml. Active theme still has unsaved changes.'; return; } await load({force:true}); if($('settingsNotice')) $('settingsNotice').textContent='Saved to nectar.toml'; }
async function saveThemeSettings(){ const select=$('settingsThemeName'); if(!select||!select.value)return; const updates={name:select.value}; const r=await fetch('/api/settings/theme',{method:'PATCH',headers:WRITE_HEADERS,body:JSON.stringify({fingerprint:state.settings.fingerprint,updates})}); const data=await r.json(); if(r.status===409){ dispatch({type:'conflict',message:'nectar.toml changed on disk. Latest theme settings loaded; choose again after review.'}); siteSettingsDirty=false; themeSettingsDirty=false; await load({force:true}); if($('themeSettingsNotice')) $('themeSettingsNotice').textContent=ui.conflictMessage; return; } if(!r.ok){ $('themeSettingsNotice').textContent=data.error||'Could not save theme'; return; } if(data.fingerprint) state.settings.fingerprint=data.fingerprint; state.settings.theme.name=updates.name; state.settings.theme.available=(state.settings.theme.available||[]).map(theme=>({...theme,active:theme.name===updates.name})); themeSettingsDirty=false; select.dataset.current=select.value; updateThemeSaveState(); if(siteSettingsDirty){ $('themeSettingsNotice').textContent='Saved active theme. Site card still has unsaved changes.'; return; } await load({force:true}); if($('themeSettingsNotice')) $('themeSettingsNotice').textContent='Saved active theme'; }
async function materializeTaxonomy(kind,slug){ const r=await fetch('/api/taxonomy/'+kind+'/'+slug+'/file',{method:'POST',headers:WRITE_HEADERS}); if(!r.ok){ alert((await r.json()).error||'Could not create taxonomy file'); return; } await load(); }
async function createItem(){ const title=prompt('Title or name'); if(!title)return; const kind=ui.view==='settings'?'posts':ui.view; const r=await fetch('/api/content',{method:'POST',headers:WRITE_HEADERS,body:JSON.stringify({kind,title})}); if(!r.ok){ alert((await r.json()).error||'Could not create file'); return; } await load(); }
function warningBadge(item){ return item.warnings&&item.warnings.length?'<span class="warnBadge">'+item.warnings.length+' warning'+(item.warnings.length===1?'':'s')+'</span>':''; }
function previewCell(item){ const preview=item.preview||{}; const cls=preview.state==='current'?'':'draft'; const label=preview.label||'Build required'; const action=preview.artifactPath?'<a class="previewLink" href="'+escapeAttr(preview.openUrl)+'" target="_blank" rel="noreferrer">Open</a>':''; return '<span class="pill '+cls+'">'+escapeHtml(label)+'</span><div class="meta">'+escapeHtml(preview.artifactPath||preview.detail||'Saved build artifact only')+'</div>'+action; }
function findSummary(kind,slug){ const list=state&&state[kind]; return list&&list.items?list.items.find(item=>item.slug===slug):null; }
function renderArtifactPreview(item){ const box=$('artifactPreview'); if(!box)return; if(!item||!item.preview){ box.classList.remove('active'); box.innerHTML=''; return; } const preview=item.preview; const canFrame=Boolean(preview.artifactPath); box.classList.toggle('active',true); box.innerHTML='<div class="previewMeta"><span>'+escapeHtml(preview.label)+' · saved build artifact</span>'+(canFrame?'<a class="previewLink" href="'+escapeAttr(preview.openUrl)+'" target="_blank" rel="noreferrer">Open</a>':'')+'</div>'+(canFrame?'<iframe class="previewFrame" title="Saved build preview" src="'+escapeAttr(preview.openUrl)+'" sandbox="'+escapeAttr((preview.sandbox?.attributes||[]).join(' '))+'" referrerpolicy="no-referrer"></iframe>':'<div class="empty">'+escapeHtml(preview.detail)+'</div>'); }
function renderEditorWarnings(){ const text=($('editBody').value||''); const warnings=[]; if(/!\[\s*\]\(/.test(text)) warnings.push('Markdown image has empty alt text.'); if(/<img\b(?![^>]*\salt=)[^>]*>/i.test(text)) warnings.push('HTML image is missing an alt attribute.'); $('editorWarnings').textContent=warnings.join(' '); $('editorWarnings').classList.toggle('active',warnings.length>0); }
function buildFrontmatter(){ const fm={...current.frontmatter}; if(current.kind==='posts'||current.kind==='pages'){ fm.title=$('editTitle').value; fm.status=$('editStatus').value; fm.updated_at=new Date().toISOString(); setOptionalFrontmatter(fm,'feature_image',normalizeMediaPath($('editFeatureImage').value)); setOptionalFrontmatter(fm,'feature_image_alt',$('editFeatureImageAlt').value.trim()); setOptionalFrontmatter(fm,'feature_image_caption',$('editFeatureImageCaption').value.trim()); } else { fm.name=$('editTitle').value; } return fm; }
function setOptionalFrontmatter(fm,key,value){ if(value) fm[key]=value; else delete fm[key]; }
function snapshotFromItem(item){ return {title:item.frontmatter.title||item.frontmatter.name||'',status:item.frontmatter.status||'published',featureImage:item.frontmatter.feature_image||'',featureImageAlt:item.frontmatter.feature_image_alt||'',featureImageCaption:item.frontmatter.feature_image_caption||'',body:item.body}; }
function editorSnapshot(){ return {title:$('editTitle').value,status:$('editStatus').value,featureImage:$('editFeatureImage').value,featureImageAlt:$('editFeatureImageAlt').value,featureImageCaption:$('editFeatureImageCaption').value,body:$('editBody').value}; }
function applyEditorSnapshot(snapshot){ $('editTitle').value=snapshot.title||''; $('editStatus').value=snapshot.status||'published'; const contentKind=current&&['posts','pages'].includes(current.kind); $('editStatus').disabled=!contentKind; ['editFeatureImage','editFeatureImageAlt','editFeatureImageCaption'].forEach(id=>$(id).disabled=!contentKind); $('editFeatureImage').value=snapshot.featureImage||''; $('editFeatureImageAlt').value=snapshot.featureImageAlt||''; $('editFeatureImageCaption').value=snapshot.featureImageCaption||''; $('editBody').value=snapshot.body||''; }
function snapshotsEqual(a,b){ return JSON.stringify(a)===JSON.stringify(b); }
function hasEditorDirty(){ return current!==null&&editorBaseline!==null&&!snapshotsEqual(editorSnapshot(),editorBaseline); }
function fingerprintToken(fingerprint){ return [fingerprint.path,fingerprint.mtimeMs,fingerprint.size].join('@'); }
function draftKey(item){ return NECTAR_DRAFT_PREFIX+encodeURIComponent(item.path)+':'+encodeURIComponent(fingerprintToken(item.fingerprint)); }
function revisionKey(item){ return NECTAR_REVISION_PREFIX+encodeURIComponent(item.path); }
function storageAreas(){ const areas=[]; try{ if(window.localStorage)areas.push(window.localStorage); }catch{} try{ if(window.sessionStorage)areas.push(window.sessionStorage); }catch{} return areas; }
function safeSet(key,value){ for(const storage of storageAreas()){ try{ storage.setItem(key,value); return true; }catch{} } return false; }
function safeRemove(key){ for(const storage of storageAreas()){ try{ storage.removeItem(key); }catch{} } }
function readStoredJson(key){ for(const storage of storageAreas()){ try{ const value=storage.getItem(key); if(value)return JSON.parse(value); }catch{} } return null; }
function keysWithPrefix(prefix){ const keys=[]; for(const storage of storageAreas()){ try{ for(let i=0;i<storage.length;i++){ const key=storage.key(i); if(key&&key.startsWith(prefix))keys.push(key); } }catch{} } return Array.from(new Set(keys)); }
function persistDraft(){ if(!current)return; if(!hasEditorDirty()){ safeRemove(currentDraftKey); pendingDraft=findDraftForCurrent(); updateRecoveryControls(); return; } const payload={kind:current.kind,slug:current.slug,path:current.path,fingerprint:current.fingerprint,at:new Date().toISOString(),snapshot:editorSnapshot()}; safeSet(currentDraftKey,JSON.stringify(payload)); pendingDraft=payload; updateRecoveryControls(); }
function findDraftForCurrent(){ if(!current)return null; const prefix=NECTAR_DRAFT_PREFIX+encodeURIComponent(current.path)+':'; const drafts=keysWithPrefix(prefix).map(key=>readStoredJson(key)).filter(Boolean); drafts.sort((a,b)=>Date.parse(b.at||'')-Date.parse(a.at||'')); return drafts[0]||null; }
function clearDraftsForCurrent(){ if(!current)return; const prefix=NECTAR_DRAFT_PREFIX+encodeURIComponent(current.path)+':'; keysWithPrefix(prefix).forEach(safeRemove); }
function recordRevision(snapshot){ if(!current)return; const revisions=readStoredJson(currentRevisionKey)||[]; revisions.push({at:new Date().toISOString(),path:current.path,kind:current.kind,slug:current.slug,...snapshot}); safeSet(currentRevisionKey,JSON.stringify(revisions.slice(-5))); updateRecoveryControls(); }
function readRevisions(){ const value=readStoredJson(currentRevisionKey); return Array.isArray(value)?value:[]; }
function updateRecoveryControls(){ const draft=pendingDraft||findDraftForCurrent(); const revisions=readRevisions(); $('restoreDraft').disabled=!draft; $('rollbackEditor').disabled=revisions.length===0; $('previewEditor').disabled=!current||!['posts','pages'].includes(current.kind); $('draftNotice').textContent=draft?'Browser draft available for '+draft.path+(fingerprintToken(draft.fingerprint)===fingerprintToken(current.fingerprint)?'.':' from an older fingerprint; compare before saving.'):''; $('draftNotice').classList.toggle('active',Boolean(draft)); $('editorHistory').textContent=revisions.length?revisions.length+' local revision(s) kept in this browser before saves.':''; $('editorHistory').classList.toggle('active',revisions.length>0); }
function restoreDraft(){ const draft=pendingDraft||findDraftForCurrent(); if(!draft)return; if(!confirm('Restore the browser draft into the editor? It will not write the file until you save.'))return; applyEditorSnapshot(draft.snapshot); $('notice').textContent='Browser draft restored. Save writes it only after fingerprint checks pass.'; renderEditorWarnings(); persistDraft(); }
function rollbackEditor(){ const revisions=readRevisions(); const revision=revisions[revisions.length-1]; if(!revision)return; if(!confirm('Restore the latest local revision into the editor? It will not write the file until you save.'))return; applyEditorSnapshot({title:revision.frontmatter.title||revision.frontmatter.name||'',status:revision.frontmatter.status||'published',featureImage:revision.frontmatter.feature_image||'',featureImageAlt:revision.frontmatter.feature_image_alt||'',featureImageCaption:revision.frontmatter.feature_image_caption||'',body:revision.body||''}); $('notice').textContent='Local revision restored into the editor. Save after review.'; renderEditorWarnings(); persistDraft(); }
function normalizeMediaPath(value){ const raw=String(value||'').trim(); if(!raw)return ''; if(/^https?:\/\//i.test(raw)||raw.startsWith('/'))return raw; return '/'+raw.replace(/^\.?\//,''); }
function insertText(before,after,placeholder){ const area=$('editBody'); const start=area.selectionStart||0; const end=area.selectionEnd||0; const selected=area.value.slice(start,end)||placeholder; area.value=area.value.slice(0,start)+before+selected+after+area.value.slice(end); const cursor=start+before.length+selected.length; area.focus(); area.setSelectionRange(cursor,cursor); renderEditorWarnings(); persistDraft(); }
function applySnippet(name){ if(name==='bold')return insertText('**','**','bold text'); if(name==='link')return insertText('[','](https://example.com)','link text'); if(name==='code')return insertText('\`','\`','code'); if(name==='heading')return insertText('\n## ','\n','Heading'); if(name==='list')return insertText('\n- ','\n','List item'); if(name==='image')return insertText('![Alt text](',')','/content/images/image.jpg'); if(name==='callout')return insertText('\n> [!NOTE]\n> ','\n','Callout text'); }
function insertMedia(){ const path=normalizeMediaPath(prompt('Image path under content/images, or an absolute URL')||''); if(!path)return; const alt=prompt('Alt text')||''; const caption=prompt('Caption (optional)')||''; insertText('',(caption?'\n\n*'+caption+'*':'')+'\n','!['+alt.replace(/]/g,'')+']('+path.replace(/\)/g,'')+')'); }
function previewEditor(){ if(!current)return; if(hasEditorDirty())$('notice').textContent='Preview opens the saved file. Save first to include current edits.'; const route=findCurrentRoute(); window.open(route,'_blank','noopener'); }
function findCurrentRoute(){ const list=current.kind==='posts'?state.posts.items:state.pages.items; const item=list.find(item=>item.slug===current.slug); return item?item.url:'/'+current.slug+'/'; }
function hasSettingsDirty(){ return siteSettingsDirty||themeSettingsDirty; }
function confirmDiscardChanges(message){ if(!(hasEditorDirty()||hasSettingsDirty()))return true; if(!confirm(message||'Discard unsaved changes?'))return false; if(current){ persistDraft(); current=null; editorBaseline=null; pendingDraft=null; $('editor').classList.remove('open'); } siteSettingsDirty=false; themeSettingsDirty=false; return true; }
function renderStatePanel(kind,message){ $('contentPanel').innerHTML=renderStatePanelHtml(kind,message); }
function renderStatePanelHtml(kind,message){ const copy={loading:['Reading files','Loading the latest saved Markdown and config state from disk.'],error:['Dashboard could not load',message||'Keep your files unchanged and refresh after fixing the reported problem.'],conflict:['External change detected',message||'The file changed on disk. Reloaded latest content so you can review before saving.'],empty:['No files match this view',message||'Try a different search, status filter, or section.']}[kind]||['Dashboard state',message||'']; const action=kind==='error'?'<button class="btn secondary" data-state-action="refresh">Refresh</button>':''; return '<div class="statePanel '+escapeAttr(kind)+'" role="status" aria-live="polite"><b>'+escapeHtml(copy[0])+'</b><p>'+escapeHtml(copy[1])+'</p>'+action+'</div>'; }
function matches(text,query){ return !query || String(text).toLowerCase().includes(query); }
function setView(next){ if(!confirmDiscardChanges('Leave this view? Unsaved settings will be discarded; unsaved editor changes stay only in this browser draft until you save.'))return; dispatch({type:'view/set',view:next}); $('search').value=''; closePalette(); load({force:true}); }
function openPalette(){ $('paletteModal').classList.add('open'); const first=$('paletteModal').querySelector('button'); if(first) first.focus(); }
function closePalette(){ $('paletteModal').classList.remove('open'); }
function date(v){ return new Date(v).toLocaleDateString(); }
function escapeHtml(v){ return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function escapeAttr(v){ return escapeHtml(v).replace(/"/g,'&quot;'); }
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('search').oninput=(event)=>{ dispatch({type:'search/set',query:event.target.value}); if(ui.view==='posts'||ui.view==='pages'){ clearTimeout(window.__nectarSearchTimer); window.__nectarSearchTimer=setTimeout(load,180); } else { render(); } };
$('density').onclick=()=>{ dispatch({type:'density/toggle'}); render(); };
$('theme').onclick=cycleTheme;
$('command').onclick=openPalette;
$('closePalette').onclick=closePalette;
document.querySelectorAll('[data-command-view]').forEach(b=>b.onclick=()=>setView(b.dataset.commandView));
document.querySelectorAll('[data-command-action]').forEach(b=>b.onclick=()=>{ closePalette(); load(); });
document.addEventListener('click',(event)=>{ if(event.target?.dataset?.stateAction==='refresh') load(); });
$('refresh').onclick=()=>load();
$('newItem').onclick=createItem;
$('closeEditor').onclick=closeEditor;
$('saveEditor').onclick=saveEditor;
$('restoreDraft').onclick=restoreDraft;
$('rollbackEditor').onclick=rollbackEditor;
$('previewEditor').onclick=previewEditor;
$('insertMedia').onclick=insertMedia;
document.querySelectorAll('[data-snippet]').forEach(b=>b.onclick=()=>applySnippet(b.dataset.snippet));
['editTitle','editStatus','editFeatureImage','editFeatureImageAlt','editFeatureImageCaption','editBody'].forEach(id=>$(id).oninput=handleEditorInput);
$('editTitle').onkeydown=(event)=>{ if(event.key==='Enter'||event.key==='ArrowDown'){ event.preventDefault(); $('editBody').focus(); } };
function closeEditor(){ if(!confirmDiscardChanges('Close editor? Unsaved changes stay only in this browser draft until you save.'))return; current=null; editorBaseline=null; pendingDraft=null; $('editor').classList.remove('open'); }
function handleEditorInput(){ renderEditorWarnings(); persistDraft(); }
document.addEventListener('keydown',(event)=>{ const key=event.key.toLowerCase(); if((event.metaKey||event.ctrlKey)&&key==='k'){ event.preventDefault(); openPalette(); } if((event.metaKey||event.ctrlKey)&&key==='s'){ event.preventDefault(); if(ui.view==='settings'&&!current){ const active=document.activeElement?.id; if(active==='settingsThemeName') saveThemeSettings(); else saveSettings(); } else { saveEditor(); } } if((event.metaKey||event.ctrlKey)&&key==='p'){ event.preventDefault(); previewEditor(); } if(event.key==='/'&&ui.view==='settings'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName||'')){ event.preventDefault(); $('settingsSearch')?.focus(); } if(event.key==='Escape'){ closePalette(); if(current)closeEditor(); } });
window.addEventListener('beforeunload',(event)=>{ if(hasEditorDirty()||hasSettingsDirty()){ event.preventDefault(); event.returnValue=''; } });
window.addEventListener('popstate',()=>{ if(!confirmDiscardChanges('Leave this view? Unsaved settings will be discarded; unsaved editor changes stay only in this browser draft until you save.')) history.pushState(null,'',location.href); });
applyUiPreferences();
new EventSource('/api/events').addEventListener('sync',()=>{ if(hasEditorDirty()||hasSettingsDirty()){ $('sync').textContent='files changed on disk; save or discard edits before refresh'; return; } load({force:true}); });
load();`;
}
