#!/usr/bin/env bun
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import matter from 'gray-matter';

// Source-of-truth lives under src/skills/<slug>/skill.md so contributors can
// edit skills as plain markdown. The compiled CLI binary cannot read from the
// source tree at runtime, so this script materialises every skill into a
// committed TS module (src/cli/skill/bundled-skills.ts) that the CLI imports.
// Mirrors the same pattern scripts/build-dashboard-bundle.ts uses for the
// dashboard JS / CSS bundle.

const SKILLS_ROOT = resolve('src/skills');
const OUTPUT_PATH = resolve('src/cli/skill/bundled-skills.ts');

interface ParsedSkill {
  slug: string;
  frontmatter: {
    name: string;
    description: string;
    version: number;
    applies_to: string[];
    triggers?: string[];
  };
  body: string;
}

async function readSkillDir(slug: string): Promise<ParsedSkill> {
  const skillPath = join(SKILLS_ROOT, slug, 'skill.md');
  const raw = await readFile(skillPath, 'utf8');
  const { data, content } = matter(raw);
  const requiredKeys = ['name', 'description', 'version', 'applies_to'] as const;
  for (const key of requiredKeys) {
    if (!(key in data)) {
      throw new Error(`Skill ${slug}: missing required frontmatter key '${key}' in ${skillPath}`);
    }
  }
  const appliesTo = data.applies_to;
  if (!Array.isArray(appliesTo) || appliesTo.some((v) => typeof v !== 'string')) {
    throw new Error(`Skill ${slug}: applies_to must be a string array`);
  }
  const triggers = data.triggers;
  if (triggers !== undefined && (!Array.isArray(triggers) || triggers.some((v) => typeof v !== 'string'))) {
    throw new Error(`Skill ${slug}: triggers must be a string array when present`);
  }
  return {
    slug,
    frontmatter: {
      name: String(data.name),
      description: String(data.description),
      version: Number(data.version),
      applies_to: appliesTo as string[],
      ...(triggers !== undefined ? { triggers: triggers as string[] } : {}),
    },
    body: content.replace(/^\n+/, '').replace(/\n+$/, '\n'),
  };
}

async function main(): Promise<void> {
  const entries = await readdir(SKILLS_ROOT, { withFileTypes: true });
  const slugs = entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();
  const skills: ParsedSkill[] = [];
  for (const slug of slugs) {
    const skillPath = join(SKILLS_ROOT, slug, 'skill.md');
    try {
      await stat(skillPath);
    } catch {
      console.warn(`Skipping ${slug}/: no skill.md`);
      continue;
    }
    skills.push(await readSkillDir(slug));
  }

  const lines: string[] = [];
  lines.push('// This file is generated by scripts/build-skill-bundle.ts.');
  lines.push('// Do not edit it by hand; update src/skills/<name>/skill.md and rerun.');
  lines.push('');
  lines.push("import type { BundledSkill } from './types.ts';");
  lines.push('');
  lines.push('export const BUNDLED_SKILLS: ReadonlyArray<BundledSkill> = [');
  for (const skill of skills) {
    lines.push('  {');
    lines.push(`    slug: ${JSON.stringify(skill.slug)},`);
    lines.push('    frontmatter: {');
    lines.push(`      name: ${JSON.stringify(skill.frontmatter.name)},`);
    lines.push(`      description: ${JSON.stringify(skill.frontmatter.description)},`);
    lines.push(`      version: ${skill.frontmatter.version},`);
    lines.push(`      applies_to: ${JSON.stringify(skill.frontmatter.applies_to)},`);
    if (skill.frontmatter.triggers !== undefined) {
      lines.push(`      triggers: ${JSON.stringify(skill.frontmatter.triggers)},`);
    }
    lines.push('    },');
    lines.push(`    body: ${JSON.stringify(skill.body)},`);
    lines.push('  },');
  }
  lines.push('];');
  lines.push('');

  await writeFile(OUTPUT_PATH, lines.join('\n'), 'utf8');
  console.log(`Wrote ${skills.length} skill(s) to ${OUTPUT_PATH}`);
  for (const skill of skills) {
    console.log(`  - ${skill.slug} v${skill.frontmatter.version}`);
  }
}

await main();
