#!/usr/bin/env bun
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const outdir = process.env.NECTAR_BUILD_OUTDIR?.trim() || 'dist';
const bundleDir = join(outdir, 'dashboard-bundle');
const generatedAssetsModule = resolve('src/cli/dashboard/bundled-assets.ts');
await mkdir(bundleDir, { recursive: true });

const jsResult = await Bun.build({
  entrypoints: ['src/cli/dashboard/web/entry.tsx'],
  outdir: bundleDir,
  target: 'browser',
  format: 'esm',
  naming: { entry: 'dashboard.js' },
  minify: true,
  sourcemap: 'none',
});

if (!jsResult.success) {
  for (const log of jsResult.logs) console.error(log);
  process.exit(1);
}

const cssIn = resolve('src/cli/dashboard/web/styles.css');
const cssOut = resolve(bundleDir, 'dashboard.css');
const tailwindBin = resolve('node_modules/.bin/tailwindcss');

const css = Bun.spawn([tailwindBin, '--input', cssIn, '--output', cssOut, '--minify'], {
  stdout: 'pipe',
  stderr: 'pipe',
});
const cssExit = await css.exited;
if (cssExit !== 0) {
  const errText = await new Response(css.stderr).text();
  console.error(errText.trim());
  process.exit(cssExit);
}

const sizes = await Promise.all(
  ['dashboard.js', 'dashboard.css'].map(async (name) => {
    const info = await stat(join(bundleDir, name));
    return `${name}: ${info.size} B`;
  }),
);
await writeFile(
  generatedAssetsModule,
  [
    '// This file is generated by scripts/build-dashboard-bundle.ts.',
    '// Do not edit it by hand; update src/cli/dashboard/web/* and rebuild the bundle.',
    '',
    'type DashboardBundleAsset = { contentType: string; body: string };',
    '',
    'export const DASHBOARD_BUNDLE_ASSETS: Partial<Record<string, DashboardBundleAsset>> = {',
    `  '/assets/dashboard.js': {`,
    `    contentType: 'application/javascript; charset=utf-8',`,
    `    body: ${JSON.stringify(await readFile(join(bundleDir, 'dashboard.js'), 'utf8'))},`,
    '  },',
    `  '/assets/dashboard.css': {`,
    `    contentType: 'text/css; charset=utf-8',`,
    `    body: ${JSON.stringify(await readFile(join(bundleDir, 'dashboard.css'), 'utf8'))},`,
    '  },',
    '};',
    '',
  ].join('\n'),
  'utf8',
);
console.log(`Built ${bundleDir}/ — ${sizes.join(', ')}; embedded ${generatedAssetsModule}`);
