#!/usr/bin/env bun
/**
 * Walks `src/render/helpers/*.ts`, extracts every `engine.hb.registerHelper(...)`
 * call, and prints a Markdown-friendly index grouped by source file. The output
 * is intended to backstop `docs/theme-reference.md` so the doc's helper table
 * can be cross-checked against the actual registration surface in CI.
 *
 * Usage:
 *   bun run docs:theme-reference            # print to stdout
 *   bun run docs:theme-reference --check    # exit 1 if helpers found here
 *                                           # are absent from theme-reference.md
 *
 * This is intentionally not a doc *generator* — the per-helper prose lives in
 * `docs/THEME_DEV.md` §5 and is hand-written. This script only enumerates the
 * names so a missing entry surfaces in code review.
 */
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';

const HELPERS_DIR = new URL('../src/render/helpers/', import.meta.url).pathname;
const REFERENCE_DOC = new URL('../docs/theme-reference.md', import.meta.url).pathname;

interface HelperEntry {
  name: string;
  file: string;
  line: number;
}

async function listHelperFiles(): Promise<string[]> {
  const entries = await readdir(HELPERS_DIR);
  return entries.filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts') && f !== 'index.ts');
}

// Matches `registerHelper(` (capturing the line) followed eventually by a
// quoted helper name. The `[\s\S]*?` non-greedy stretch lets the name live on
// the same line or on the next 1-3 lines for the multi-arg call style. We
// dedupe per file so an overload that registers under two names still
// reports once per name.
const REGISTER_RE = /registerHelper\(\s*['"]([a-z_]+)['"]/g;
const REGISTER_MULTI_RE = /registerHelper\(\s*\n\s*['"]([a-z_]+)['"]/g;

async function extract(file: string): Promise<HelperEntry[]> {
  const path = join(HELPERS_DIR, file);
  const src = await readFile(path, 'utf8');
  const seen = new Map<string, number>();

  // Single-line: `engine.hb.registerHelper('foo', function ...)`.
  for (const m of src.matchAll(REGISTER_RE)) {
    const name = m[1] as string;
    if (seen.has(name)) continue;
    const line = src.slice(0, m.index ?? 0).split('\n').length;
    seen.set(name, line);
  }
  // Multi-line: `engine.hb.registerHelper(\n  'foo',\n  function ...`.
  for (const m of src.matchAll(REGISTER_MULTI_RE)) {
    const name = m[1] as string;
    if (seen.has(name)) continue;
    const line = src.slice(0, m.index ?? 0).split('\n').length;
    seen.set(name, line);
  }
  return [...seen.entries()].map(([name, line]) => ({ name, file, line }));
}

async function collect(): Promise<HelperEntry[]> {
  const files = await listHelperFiles();
  const all: HelperEntry[] = [];
  for (const file of files.sort()) {
    all.push(...(await extract(file)));
  }
  return all;
}

function printMarkdown(entries: HelperEntry[]): void {
  const byFile = new Map<string, HelperEntry[]>();
  for (const e of entries) {
    const bucket = byFile.get(e.file);
    if (bucket) bucket.push(e);
    else byFile.set(e.file, [e]);
  }
  console.log('<!-- Generated by `bun run docs:theme-reference`. Do not edit by hand. -->');
  console.log('');
  for (const [file, list] of byFile) {
    console.log(`### \`src/render/helpers/${file}\``);
    console.log('');
    for (const entry of list.sort((a, b) => a.name.localeCompare(b.name))) {
      console.log(`- \`{{${entry.name}}}\` — ${file}:${entry.line}`);
    }
    console.log('');
  }
}

async function checkDoc(entries: HelperEntry[]): Promise<number> {
  let doc: string;
  try {
    doc = await readFile(REFERENCE_DOC, 'utf8');
  } catch {
    console.error(`Missing ${REFERENCE_DOC}. Create it (or run without --check).`);
    return 1;
  }
  const missing: string[] = [];
  for (const e of entries) {
    // Match either `{{name` or `{{#name` in the doc, since block helpers are
    // shown with the leading `#`. Either form proves the helper has prose.
    const inline = `{{${e.name}`;
    const block = `{{#${e.name}`;
    if (!doc.includes(inline) && !doc.includes(block)) missing.push(e.name);
  }
  if (missing.length === 0) {
    console.log(`OK — all ${entries.length} helpers are mentioned in theme-reference.md.`);
    return 0;
  }
  console.error('The following helpers are registered but missing from theme-reference.md:');
  for (const name of missing) console.error(`  - {{${name}}}`);
  console.error('');
  console.error('Add them to `docs/theme-reference.md` under the appropriate section,');
  console.error('or to `docs/THEME_DEV.md` §5 if a per-helper prose entry is needed.');
  return 1;
}

const args = process.argv.slice(2);
const entries = await collect();
if (args.includes('--check')) {
  process.exit(await checkDoc(entries));
}
printMarkdown(entries);
