// Curated emoji set for the callout icon picker. Deliberately not the full
// Unicode catalogue — a generous, searchable subset keeps the dashboard bundle
// lean while covering the icons callouts actually use. Each entry is
// `[emoji, keywords]`; keywords drive the search box and are space-separated.

interface EmojiCategory {
  name: string;
  emojis: readonly (readonly [string, string])[];
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    name: 'Common',
    emojis: [
      ['💡', 'idea light bulb tip hint'],
      ['⚠️', 'warning caution alert'],
      ['✏️', 'pencil edit write note'],
      ['📝', 'memo note writing'],
      ['✅', 'check done yes success ok'],
      ['❌', 'cross no error fail wrong'],
      ['ℹ️', 'info information'],
      ['❓', 'question help'],
      ['❗', 'exclamation important'],
      ['🔥', 'fire hot trending'],
      ['⭐', 'star favorite'],
      ['💬', 'comment speech chat quote'],
      ['📌', 'pin pushpin important'],
      ['🚀', 'rocket launch ship fast'],
      ['🎯', 'target goal aim'],
      ['🔑', 'key important access'],
      ['🛑', 'stop danger'],
      ['👉', 'point right'],
      ['📣', 'announce megaphone shout'],
      ['🧠', 'brain think smart'],
    ],
  },
  {
    name: 'Smileys',
    emojis: [
      ['😀', 'grin happy smile'],
      ['😃', 'happy smile joy'],
      ['😄', 'laugh happy'],
      ['😁', 'grin beaming'],
      ['😅', 'sweat nervous laugh'],
      ['😂', 'laugh tears joy lol'],
      ['🙂', 'slight smile'],
      ['😉', 'wink'],
      ['😊', 'blush happy smile'],
      ['😍', 'love heart eyes'],
      ['😎', 'cool sunglasses'],
      ['🤔', 'think hmm consider'],
      ['🤨', 'skeptic eyebrow'],
      ['😐', 'neutral meh'],
      ['😴', 'sleep tired'],
      ['😮', 'wow surprise'],
      ['😢', 'cry sad'],
      ['😡', 'angry mad'],
      ['🤯', 'mind blown shock'],
      ['🥳', 'party celebrate'],
      ['😱', 'scream shock fear'],
      ['🙃', 'upside down silly'],
    ],
  },
  {
    name: 'People',
    emojis: [
      ['👍', 'thumbs up like yes good'],
      ['👎', 'thumbs down dislike no'],
      ['👋', 'wave hello hi bye'],
      ['🙌', 'raise hands celebrate'],
      ['👏', 'clap applause'],
      ['🙏', 'pray thanks please'],
      ['💪', 'muscle strong'],
      ['🤝', 'handshake deal'],
      ['👀', 'eyes look watch'],
      ['🫶', 'heart hands love'],
      ['✌️', 'peace victory'],
      ['🤞', 'fingers crossed luck'],
      ['👌', 'ok perfect'],
      ['🤙', 'call shaka'],
      ['🧑‍💻', 'developer coder programmer'],
      ['🧗', 'climb challenge'],
    ],
  },
  {
    name: 'Nature',
    emojis: [
      ['🌟', 'glow star sparkle'],
      ['✨', 'sparkles shine magic'],
      ['⚡', 'lightning fast power'],
      ['🌈', 'rainbow'],
      ['☀️', 'sun sunny'],
      ['🌙', 'moon night'],
      ['🔆', 'bright'],
      ['💧', 'water drop'],
      ['🌊', 'wave ocean sea'],
      ['🌱', 'seedling grow plant'],
      ['🌳', 'tree nature'],
      ['🍀', 'clover luck'],
      ['🌸', 'blossom flower'],
      ['🐛', 'bug insect'],
      ['🐝', 'bee'],
      ['🦋', 'butterfly'],
      ['🐱', 'cat'],
      ['🐶', 'dog'],
    ],
  },
  {
    name: 'Food',
    emojis: [
      ['☕', 'coffee tea drink'],
      ['🍵', 'tea matcha'],
      ['🍺', 'beer drink'],
      ['🍷', 'wine drink'],
      ['🍰', 'cake dessert'],
      ['🍪', 'cookie'],
      ['🍎', 'apple fruit'],
      ['🍌', 'banana fruit'],
      ['🍕', 'pizza food'],
      ['🍔', 'burger food'],
      ['🍜', 'noodle ramen food'],
      ['🍱', 'bento food'],
      ['🧁', 'cupcake'],
      ['🍫', 'chocolate'],
      ['🍯', 'honey'],
      ['🧂', 'salt'],
    ],
  },
  {
    name: 'Activity',
    emojis: [
      ['🎉', 'party celebrate tada'],
      ['🎊', 'confetti celebrate'],
      ['🏆', 'trophy win award'],
      ['🥇', 'gold medal first'],
      ['🎁', 'gift present'],
      ['🎨', 'art paint design'],
      ['🎵', 'music note'],
      ['🎮', 'game play'],
      ['⚽', 'soccer ball sport'],
      ['🏀', 'basketball sport'],
      ['🎲', 'dice random game'],
      ['🧩', 'puzzle piece'],
      ['🎬', 'movie film clapper'],
      ['📷', 'camera photo'],
    ],
  },
  {
    name: 'Travel',
    emojis: [
      ['✈️', 'plane flight travel'],
      ['🚗', 'car drive'],
      ['🚆', 'train'],
      ['🚲', 'bike bicycle'],
      ['🗺️', 'map travel'],
      ['🧭', 'compass direction'],
      ['🏠', 'home house'],
      ['🏢', 'office building'],
      ['🏝️', 'island beach'],
      ['⛰️', 'mountain'],
      ['🌍', 'earth globe world'],
      ['🚦', 'traffic light signal'],
      ['📍', 'location pin place'],
      ['🛰️', 'satellite'],
    ],
  },
  {
    name: 'Objects',
    emojis: [
      ['📚', 'books read docs reference'],
      ['📖', 'book open read'],
      ['📄', 'document page file'],
      ['📁', 'folder files'],
      ['📦', 'package box'],
      ['🔒', 'lock secure private'],
      ['🔓', 'unlock open'],
      ['🔔', 'bell notify alert'],
      ['🔕', 'mute silent'],
      ['💻', 'laptop computer code'],
      ['🖥️', 'desktop monitor'],
      ['📱', 'phone mobile'],
      ['⌚', 'watch time'],
      ['🔋', 'battery power'],
      ['🔌', 'plug power'],
      ['🛠️', 'tools fix build'],
      ['⚙️', 'gear settings config'],
      ['🧰', 'toolbox'],
      ['🔍', 'search magnify find'],
      ['💰', 'money cash bag'],
      ['💳', 'card payment'],
      ['📈', 'chart growth up trend'],
      ['📉', 'chart down decline'],
      ['📊', 'bar chart data'],
      ['🗂️', 'index files'],
      ['📅', 'calendar date'],
      ['⏰', 'alarm clock time'],
      ['⏳', 'hourglass wait time'],
      ['🧾', 'receipt invoice'],
      ['✂️', 'scissors cut'],
      ['📎', 'paperclip attach'],
      ['🔗', 'link chain url'],
      ['🏷️', 'tag label'],
    ],
  },
  {
    name: 'Symbols',
    emojis: [
      ['❤️', 'heart love red'],
      ['🧡', 'orange heart'],
      ['💛', 'yellow heart'],
      ['💚', 'green heart'],
      ['💙', 'blue heart'],
      ['💜', 'purple heart'],
      ['✔️', 'check mark yes'],
      ['➡️', 'arrow right next'],
      ['⬅️', 'arrow left back'],
      ['⬆️', 'arrow up'],
      ['⬇️', 'arrow down'],
      ['🔁', 'repeat loop'],
      ['🔂', 'repeat one'],
      ['➕', 'plus add'],
      ['➖', 'minus remove'],
      ['✖️', 'multiply times'],
      ['♻️', 'recycle reuse'],
      ['🔞', 'eighteen restricted'],
      ['💯', 'hundred perfect score'],
      ['🆕', 'new'],
      ['🆗', 'ok'],
      ['🚫', 'no forbidden ban'],
      ['⛔', 'no entry stop'],
      ['💥', 'boom collision impact'],
      ['💢', 'anger'],
      ['❇️', 'sparkle'],
    ],
  },
];
